@startuml
title 系统资源访问时序图
actor 用户

用户 ->系统: 登录
/'系统生命线开始'/
activate 系统
系统 -> 系统: 取客户code

系统 -->用户: 获取指定资源(菜单、table)

用户 -> 系统: 获取对应code信息
系统 --> 用户: 对应响应
用户 ->系统: 注销
系统 -->用户:清理资源
/'用户生命周期结束'/
deactivate 系统
@enduml